In [ ]:
#Fundamental concepts of tensors 


#Importing tensorflow!!
import tensorflow as tf 
print(tf.__version__)

2.11.0


In [ ]:
# Creating tensors!

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check dimensions of the tensor

scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Create a matrix 
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Creating a tensor

tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,27,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 27, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#Creating a tensor with tf.variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
unchangeable_tensor, changeable_tensor


#Changing elements in changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

# While creating a tensor with tf.Variable, you can modify it.
# While creating a tensor with tf.constant, you can't modify it.

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(7) # sets seed for reproductibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(10)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.29604465, -0.21134205],
       [ 0.01063002,  1.5165398 ],
       [ 0.27305737, -0.29925638]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [ ]:
#Shuffling the tensor values!!
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1,25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
#Creating a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,  rank_4_tensor.ndim,  tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimenstions : ", rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements alond the 0 axis: ", rank_4_tensor[0])
print("Elements in the last index: ", rank_4_tensor[-1])
print("Total numer of elements in the tensor: ",tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimenstions :  4
Shape of tensor:  (2, 3, 4, 5)
Elements alond the 0 axis:  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Elements in the last index:  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total numer of elements in the tensor:  120


In [ ]:
#Indexing tensors

#Get the first two elements of each dimension

list = [1,2,3,4,5]
list[:2]
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],[2,3]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

In [ ]:
#Get last item of each row 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [ ]:
#Altering the size of the tensor!!
rank_3_tensor =rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [ ]:
#Another way of adding extra dimension of rank_2_tensor
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  3]]], dtype=int32)>

In [ ]:
#Tensor Operations!!
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1,1],[1,1]])
tensor+tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 4,  5]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#Tensor-flow built-in functions 
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.add(tensor,tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 4,  5]], dtype=int32)>

In [ ]:
#Matrix Multiplication
tf.multiply(tensor,tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor2 = tf.constant([[2,3],[4,5]])
tf.multiply(tensor,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 21],
       [12, 20]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
t1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [ ]:
t2 = tf.constant([[3,5],[6,7],[1,8]])
t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [ ]:
tf.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#Matrix Mul with different shapes!!
x = tf.constant([[1,2],[3,4],[5,6]])
y = tf.constant([[7,8],[9,10],[11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
t1 @ t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(x,shape=(2,3)) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.transpose(x),tf.reshape(x,shape=(2,3)),x

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [ ]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#Perform matrix multiplication with tensordot()
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#Perform matrix multiplication with transposing y
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#Check the value of y and rehsape y and transpose y
print("Normal y: ", y)
print("Reshaped y: ", tf.reshape(y,shape=(2,3)))
print("Transposed y: ", tf.transpose(y))

Normal y:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Reshaped y:  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Transposed y:  tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
#Changing the datatype of a tensor!!
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,4])
C.dtype

tf.int32

In [ ]:
D = tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([7., 4.], dtype=float16)>,
 tf.float16)

In [ ]:
E = tf.cast(C,dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7., 4.], dtype=float32)>,
 tf.float32)

In [ ]:
#Aggregation



F = tf.constant([-1,-2])
F,tf.abs(F)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [ ]:
G = tf.constant([[1,2],[5,3],[10,7],[0,4]])
tf.reduce_max(G),tf.reduce_min(G),tf.reduce_mean(G),tf.reduce_sum(G)


(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=32>)

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(G), tf.math.reduce_std(tf.cast(G, dtype=tf.float32))

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([15,  3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.082207>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.9370039, 1.8708287], dtype=float32)>)

In [ ]:
H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.4920913 , 0.6705848 , 0.08583224, 0.21306682, 0.15107548,
       0.04895198, 0.63222444, 0.6570554 , 0.01653647, 0.76964796,
       0.28211522, 0.49321413, 0.69883156, 0.39800513, 0.1402446 ,
       0.5807916 , 0.39105964, 0.4578563 , 0.49515438, 0.21729982,
       0.6649177 , 0.9535117 , 0.53260493, 0.73216975, 0.6709511 ,
       0.89878464, 0.7838266 , 0.63601875, 0.91660106, 0.05445516,
       0.80904186, 0.00993884, 0.5972105 , 0.7263868 , 0.02550995,
       0.94523287, 0.9811009 , 0.32621765, 0.09952581, 0.30045354,
       0.0938139 , 0.4997803 , 0.8138944 , 0.22635138, 0.07764137,
       0.79017246, 0.72513855, 0.23930764, 0.57776   , 0.10994267],
      dtype=float32)>

In [ ]:
tf.argmax(H) # positional maximum


<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [ ]:
#Squeezing the tensors (removing all single dimensions)
tf.random.set_seed(42)
I = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
I

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
I_squeezed = tf.squeeze(I)
I_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#One-hot encoding!!
list1 = [0,1,2,3]
tf.one_hot(list1,depth=4)
#IF you want other values than 0s and 1s, use on-value for 1 and off-value for 0s

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
J = tf.range(1,10)
J,tf.square(J),tf.sqrt(tf.cast(J,dtype=tf.float32)),tf.math.log(tf.cast(I,dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[-0.40862694, -0.818695  , -1.0416201 , -0.7668313 ,
            -3.3914328 , -0.37881485, -0.3009464 , -0.13645622,
            -1.4857774 , -1.4997011 , -1.1699319 , -0.32526514,
            -2.0159998 , -0.6013634 , -0.5540658 , -0.10571226,
            -4.6602955 , -0.6515625 , -0.45484787, -1.612802  ,
            -0.31550223, -0.60543936, -2.229655  , -0.39051828,
            -0.4150969 , -1.0878195 , -0.50846565, -1.5576724 ,
            -0.15930387, -0.8195685 , -0.05284442, -1.4374784 ,
            -0.20850994, -0.641809  , -0.70459646, -

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
#EXERCISES!!!!

a = tf.constant(2)
a,a.shape,a.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=2>, TensorShape([]), 0)

In [ ]:
b = tf.constant([1,2])
b,b.shape,b.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 TensorShape([2]),
 1)

In [ ]:
c = tf.constant([[1,2],[3,4]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
d = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
e = tf.random.uniform(shape=(5,300))
e

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [ ]:
tf.random.set_seed(92)
f = tf.random.uniform(shape=(5,300))
f

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6533636 , 0.51050127, 0.03962529, ..., 0.92692816, 0.02980304,
        0.98432636],
       [0.07144916, 0.21588099, 0.9920709 , ..., 0.4005462 , 0.6267004 ,
        0.87641513],
       [0.7118727 , 0.04551661, 0.22374046, ..., 0.06763983, 0.24725378,
        0.3424493 ],
       [0.8601757 , 0.67280567, 0.48945093, ..., 0.17277265, 0.7523123 ,
        0.48176706],
       [0.81554914, 0.9643389 , 0.9023224 , ..., 0.95340765, 0.8759731 ,
        0.05297053]], dtype=float32)>

In [ ]:
g = tf.matmul(tf.transpose(e),f)
g

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[2.3437743, 1.7465663, 1.4129492, ..., 1.6085564, 1.6017826,
        1.4071268],
       [1.7465663, 1.6919049, 1.4440318, ..., 1.5983975, 1.5126562,
        1.0825056],
       [1.4129492, 1.4440318, 2.0895827, ..., 1.3940786, 1.8368629,
        1.2686877],
       ...,
       [1.6085564, 1.5983975, 1.3940786, ..., 1.9630446, 1.2605104,
        1.4203465],
       [1.6017826, 1.5126562, 1.8368629, ..., 1.2605104, 1.7880787,
        1.0720975],
       [1.4071268, 1.0825056, 1.2686877, ..., 1.4203465, 1.0720975,
        2.0891788]], dtype=float32)>

In [ ]:
tf.random.set_seed(42)
h = tf.random.uniform(shape=(224,224,3))
h

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [ ]:
tf.reduce_max(h,axis=1),tf.reduce_min(h,axis=1)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[0.9982879 , 0.991555  , 0.99890864],
        [0.9963852 , 0.99686027, 0.99524415],
        [0.99798036, 0.99789786, 0.9771793 ],
        [0.9925841 , 0.9995371 , 0.996261  ],
        [0.99925447, 0.99854064, 0.98959684],
        [0.99632823, 0.9975462 , 0.9966078 ],
        [0.99893224, 0.99789345, 0.9986447 ],
        [0.99387276, 0.99100804, 0.99803686],
        [0.99614084, 0.99962425, 0.99817014],
        [0.9990084 , 0.99642086, 0.9947417 ],
        [0.99766946, 0.99010587, 0.9985434 ],
        [0.99462116, 0.9989265 , 0.9968679 ],
        [0.9953896 , 0.99844146, 0.997231  ],
        [0.9752687 , 0.99830484, 0.98452115],
        [0.9964744 , 0.99982226, 0.99907696],
        [0.99845874, 0.9961201 , 0.99886775],
        [0.9960511 , 0.99431336, 0.9901949 ],
        [0.99995625, 0.9980805 , 0.99942625],
        [0.97499347, 0.9930481 , 0.9978708 ],
        [0.998369  , 0.99853635, 0.9970608 ],
        [0.9999449 , 0.997383

In [ ]:
tf.random.set_seed(42)
h = tf.random.uniform(shape=(1,224,224,3))
tf.squeeze(h)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [ ]:
i = tf.constant([1,2,3,4,5,6,7,8,9])
tf.argmin(i)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.one_hot(i,depth=9)

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>